%%{init: {'theme': 'base', 'themeVariables': {"pieOpacity":0.5}}}%%
pie showData title Average weekly story point velocity
  "Germaine Cat": 8.3
  "Anna Field": 15.4
  "Joseph Chuck": 4.9
  "His Lordship Grantor": 5.3
