%%{init: {'theme': 'base', 'themeVariables': {"pieStrokeColor":"white","pieOuterStrokeColor":"white","pieSectionTextColor":"white","pieOpacity":1,"pie1":"#43acd9","pie2":"#f15a50","pie3":"#4b0082","pie4":"#9c1de9","pie5":"#ff1493","pie6":"#038411"}}}%%
pie showData title Story points by status
  "Done": 262
  "To Do": 129
  "In test": 87
  "Ready for QA": 46
  "Blocked": 20
  "In Progress": 20
