%%{init: { 'width': 900 }}%%
work-item-movement
  title 'Work Item Changes'
  columns [Not Existing, Draft, To Do, In Progress, In Review, In Test, Done]
  PJ-633 Not Existing: 0 -> Draft: 1
  PJ-491 In Review: 3 -> Done: 3
  PJ-15 In Progress: 1 -> In Progress: 2
  PJ-1 In Review: 8 -> Draft: 5
  PJ-481 Done: 3 -> Done: 5
